<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\{Indicator, Theme};

class IndicatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('indicators')->delete();

        $indicators = [
            // Education Development Indicators
            [
                'code' => 'EDU_001',
                'name' => 'Primary School Enrollment Rate',
                'description' => 'Percentage of school-age children enrolled in primary education',
                'theme_code' => 'EDU',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 85.5,
                'target_value' => 95.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Ministry of Education Statistics',
                'calculation_method' => '(Number of enrolled children / Total school-age children) × 100',
                'is_active' => true,
            ],
            [
                'code' => 'EDU_002',
                'name' => 'Student-Teacher Ratio',
                'description' => 'Average number of students per teacher in primary schools',
                'theme_code' => 'EDU',
                'type' => 'QUANTITATIVE',
                'unit' => 'RATIO',
                'unit_label' => 'students:teacher',
                'baseline_value' => 45.0,
                'target_value' => 35.0,
                'direction' => 'DECREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'School Records',
                'calculation_method' => 'Total students / Total teachers',
                'is_active' => true,
            ],
            [
                'code' => 'EDU_003',
                'name' => 'School Infrastructure Quality',
                'description' => 'Assessment of school facilities and learning environment quality',
                'theme_code' => 'EDU',
                'type' => 'QUALITATIVE',
                'unit' => 'SCORE',
                'unit_label' => 'points',
                'baseline_value' => 65.0,
                'target_value' => 85.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'School Inspection Reports',
                'calculation_method' => 'Based on infrastructure assessment criteria',
                'is_active' => true,
            ],

            // Healthcare Services Indicators
            [
                'code' => 'HEA_001',
                'name' => 'Maternal Mortality Rate',
                'description' => 'Number of maternal deaths per 100,000 live births',
                'theme_code' => 'HEA',
                'type' => 'QUANTITATIVE',
                'unit' => 'RATE',
                'unit_label' => 'per 100,000',
                'baseline_value' => 320.0,
                'target_value' => 150.0,
                'direction' => 'DECREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Health Facility Records',
                'calculation_method' => '(Maternal deaths / Live births) × 100,000',
                'is_active' => true,
            ],
            [
                'code' => 'HEA_002',
                'name' => 'Immunization Coverage',
                'description' => 'Percentage of children under 5 fully immunized',
                'theme_code' => 'HEA',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 78.0,
                'target_value' => 95.0,
                'direction' => 'INCREASE',
                'frequency' => 'QUARTERLY',
                'data_source' => 'Health Center Records',
                'calculation_method' => '(Fully immunized children / Total children under 5) × 100',
                'is_active' => true,
            ],
            [
                'code' => 'HEA_003',
                'name' => 'Health Facility Access',
                'description' => 'Percentage of population within 5km of health facility',
                'theme_code' => 'HEA',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 72.0,
                'target_value' => 90.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'GIS Mapping',
                'calculation_method' => 'Population within 5km / Total population × 100',
                'is_active' => true,
            ],

            // Infrastructure Development Indicators
            [
                'code' => 'INF_001',
                'name' => 'Road Network Coverage',
                'description' => 'Kilometers of all-weather roads',
                'theme_code' => 'INF',
                'type' => 'QUANTITATIVE',
                'unit' => 'KILOMETERS',
                'unit_label' => 'km',
                'baseline_value' => 125.0,
                'target_value' => 200.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Public Works Department',
                'calculation_method' => 'Total length of all-weather roads',
                'is_active' => true,
            ],
            [
                'code' => 'INF_002',
                'name' => 'Water Supply Coverage',
                'description' => 'Percentage of households with access to clean water',
                'theme_code' => 'INF',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 68.0,
                'target_value' => 95.0,
                'direction' => 'INCREASE',
                'frequency' => 'QUARTERLY',
                'data_source' => 'Water Authority Records',
                'calculation_method' => 'Households with clean water / Total households × 100',
                'is_active' => true,
            ],
            [
                'code' => 'INF_003',
                'name' => 'Electricity Access',
                'description' => 'Percentage of households with electricity connection',
                'theme_code' => 'INF',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 45.0,
                'target_value' => 85.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Utility Company Records',
                'calculation_method' => 'Households with electricity / Total households × 100',
                'is_active' => true,
            ],

            // Agricultural Development Indicators
            [
                'code' => 'AGR_001',
                'name' => 'Agricultural Productivity',
                'description' => 'Average crop yield per hectare for major crops',
                'theme_code' => 'AGR',
                'type' => 'QUANTITATIVE',
                'unit' => 'YIELD',
                'unit_label' => 'tons/hectare',
                'baseline_value' => 2.8,
                'target_value' => 4.5,
                'direction' => 'INCREASE',
                'frequency' => 'SEASONALLY',
                'data_source' => 'Agricultural Extension Services',
                'calculation_method' => 'Total production / Total cultivated area',
                'is_active' => true,
            ],
            [
                'code' => 'AGR_002',
                'name' => 'Farmer Training Coverage',
                'description' => 'Percentage of farmers receiving agricultural training',
                'theme_code' => 'AGR',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 35.0,
                'target_value' => 75.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Training Records',
                'calculation_method' => 'Trained farmers / Total farmers × 100',
                'is_active' => true,
            ],
            [
                'code' => 'AGR_003',
                'name' => 'Market Access Improvement',
                'description' => 'Number of farmers with access to formal markets',
                'theme_code' => 'AGR',
                'type' => 'QUANTITATIVE',
                'unit' => 'COUNT',
                'unit_label' => 'farmers',
                'baseline_value' => 450,
                'target_value' => 1200,
                'direction' => 'INCREASE',
                'frequency' => 'QUARTERLY',
                'data_source' => 'Market Records',
                'calculation_method' => 'Count of farmers selling to formal markets',
                'is_active' => true,
            ],

            // Environmental Protection Indicators
            [
                'code' => 'ENV_001',
                'name' => 'Forest Cover',
                'description' => 'Percentage of land area covered by forest',
                'theme_code' => 'ENV',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 15.0,
                'target_value' => 25.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Forest Department',
                'calculation_method' => 'Forest area / Total land area × 100',
                'is_active' => true,
            ],
            [
                'code' => 'ENV_002',
                'name' => 'Waste Management Coverage',
                'description' => 'Percentage of households with proper waste disposal',
                'theme_code' => 'ENV',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 42.0,
                'target_value' => 80.0,
                'direction' => 'INCREASE',
                'frequency' => 'QUARTERLY',
                'data_source' => 'Environmental Health Records',
                'calculation_method' => 'Households with proper waste disposal / Total households × 100',
                'is_active' => true,
            ],
            [
                'code' => 'ENV_003',
                'name' => 'Renewable Energy Adoption',
                'description' => 'Number of households using renewable energy sources',
                'theme_code' => 'ENV',
                'type' => 'QUANTITATIVE',
                'unit' => 'COUNT',
                'unit_label' => 'households',
                'baseline_value' => 120,
                'target_value' => 500,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Energy Survey',
                'calculation_method' => 'Count of households using renewable energy',
                'is_active' => true,
            ],

            // Economic Development Indicators
            [
                'code' => 'ECO_001',
                'name' => 'Small Business Growth',
                'description' => 'Number of registered small and medium enterprises',
                'theme_code' => 'ECO',
                'type' => 'QUANTITATIVE',
                'unit' => 'COUNT',
                'unit_label' => 'SMEs',
                'baseline_value' => 85,
                'target_value' => 200,
                'direction' => 'INCREASE',
                'frequency' => 'QUARTERLY',
                'data_source' => 'Business Registration Office',
                'calculation_method' => 'Count of registered SMEs',
                'is_active' => true,
            ],
            [
                'code' => 'ECO_002',
                'name' => 'Employment Rate',
                'description' => 'Percentage of working-age population employed',
                'theme_code' => 'ECO',
                'type' => 'QUANTITATIVE',
                'unit' => 'PERCENTAGE',
                'unit_label' => '%',
                'baseline_value' => 65.0,
                'target_value' => 80.0,
                'direction' => 'INCREASE',
                'frequency' => 'QUARTERLY',
                'data_source' => 'Labor Force Survey',
                'calculation_method' => 'Employed population / Working-age population × 100',
                'is_active' => true,
            ],
            [
                'code' => 'ECO_003',
                'name' => 'Tourism Revenue',
                'description' => 'Annual revenue from tourism activities',
                'theme_code' => 'ECO',
                'type' => 'QUANTITATIVE',
                'unit' => 'CURRENCY',
                'unit_label' => 'TZS millions',
                'baseline_value' => 150.0,
                'target_value' => 500.0,
                'direction' => 'INCREASE',
                'frequency' => 'ANNUALLY',
                'data_source' => 'Tourism Board Records',
                'calculation_method' => 'Total tourism revenue',
                'is_active' => true,
            ],
        ];

        foreach ($indicators as $indicator) {
            $themeId = Theme::where('code', $indicator['theme_code'])->first()->id;
            unset($indicator['theme_code']);
            $indicator['theme_id'] = $themeId;
            
            Indicator::create($indicator);
        }

        $this->command->info('✓ Indicators seeded successfully!');
    }
}
