---
deployment:
  tasks:
    - export APPPATH=/home/kmcserver/laravelapp
    - export PUBLICPATH=/home/kmcserver/public_html

    # Create laravelapp folder
    - /bin/mkdir -p $APPPATH

    # Remove old app files except env/vendor/node_modules
    - find $APPPATH -mindepth 1 -maxdepth 1 ! -name ".env" ! -name "vendor" ! -name "node_modules" -exec rm -rf {} \;

    # Copy new code into laravelapp
    - tar -cf - --exclude='.env' --exclude='storage' --exclude='vendor' --exclude='node_modules' . | (cd $APPPATH && tar -xf -)

    # Composer install
    - cd $APPPATH
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
    
    # Node install and build
    - cd $APPPATH
    - export PATH=/opt/alt/alt-nodejs22/root/usr/bin:$PATH

    - node -v
    - npm -v

    - npm install
    - npm run build


    # Clean public_html
    - /bin/rm -rf $PUBLICPATH/*
    - /bin/mkdir -p $PUBLICPATH

    # Copy public content to public_html
    - /bin/cp -R $APPPATH/public/* $PUBLICPATH/

    #keep only manifest.json in public/build folder
    - find $APPPATH/public -mindepth 1 -maxdepth 1 ! -name "build" -exec rm -rf {} \;
    - find $APPPATH/public/build -type f ! -name "manifest.json" -delete

    # Permissions
    - /bin/chmod -R 775 $APPPATH/storage $APPPATH/bootstrap/cache

    # Fix index.php paths
    - /bin/sed -i "s|__DIR__.'/../vendor/autoload.php'|__DIR__.'/../laravelapp/vendor/autoload.php'|g" $PUBLICPATH/index.php
    - /bin/sed -i "s|__DIR__.'/../bootstrap/app.php'|__DIR__.'/../laravelapp/bootstrap/app.php'|g" $PUBLICPATH/index.php

    # Cache optimize
    - cd $APPPATH
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache

    # Storage link
    - /usr/local/bin/php artisan storage:link
